import BackgroundVideo from '@/Components/BackgroundVideo'
import  SideBar  from '@/Components/SidebarMenu/SideBar'
import { StaticIntro } from '@/Components/StaticIntro'
import Head from 'next/head'
import Image from 'next/image'
import { HomeMain } from '@/Components/Home/HomeMain'
import { About } from '@/Components/About/About'
import {Resume} from '@/Components/Resume/Resume'
import { Services } from '@/Components/Services/Services'
import { Skills } from '@/Components/SKILLS/Skills'
import { Portfolio } from '@/Components/Portfolios/Portfolio'
import { Testimonial } from '@/Components/Testimonial/Testimonial'
import  Contact  from '@/Components/Contact/Contact'
export default function Home() {
  return (
    <>
      <Head>
        <title>Taha FrontEnd Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 <BackgroundVideo/>
 <SideBar/>
      <StaticIntro/>
     <HomeMain/>
  <About/>
<Resume/>
<Services/>
<Skills/>
<Portfolio/>
<Testimonial/>
<Contact/>
    </>
  )
}
